### ISSUE TITLE
From C Introduction

### ISSUE THREAD

**Issue by kenstaut** [vladyslav2/gfwhitelabels#1971]
"If Yes, Explain" box does not appear until after i have put credit card information in.  It should always appear

![image](https://cloud.githubusercontent.com/assets/21956276/21075745/996d39cc-bee7-11e6-9285-b66abca024c5.png)

**Comment by arthuryip723** [comment]
Similar to #1963 , according to Ken's requirement, we would like the default value from the model (for newly registered user) to be empty, so that the user will have to choose the answer manually the first time in this page. We should fix this one along with #1963.
If there are any other questions, please comment here to let me know. Thanks.
@vladyslav2
